### ISSUE TITLE
Pass custom icons through to search bar

### ISSUE THREAD

**Issue by roryschadler** [melloware/react-logviewer#10]
#5 added custom icons, but they aren't passed from `<LazyLog />` through to `<SearchBar />`. ~Updating with PR shortly~

Edit: PR #11

**Comment by melloware** [comment]
Whoops!  Nice catch and thanks for the PR!

**Comment by melloware** [comment]
5.0.2 published to NPM!

**Comment by roryschadler** [comment]
Thank you for the quick turnaround!
