### ISSUE TITLE
Prop `follow` does not work

### ISSUE THREAD

**Issue by RazerM** [melloware/react-logviewer#14]
The `follow` prop is not working for me, I have tried it with and without `<ScrollFollow>`. The log viewer just stays at the top without scrolling to show new lines.

Here is a codesandbox with the test case, although you have to provide your own websocket. I'm not sure if `follow` is meant to work when changing `text`, but that didn't work either.

[![Edit codesandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/stupefied-moon-42kkqp)

**Comment by RazerM** [comment]
I don't think so, follow appears to work in the original version of the library.

**Comment by melloware** [comment]
Ahh most likely then an upgrade from `react-virtualized` which is deprecated to `react-window` ?

**Comment by melloware** [comment]
I would think the method to debug would be here: https://github.com/melloware/react-logviewer/blob/2fc93e33c0531af29b4c3d77a16bcf759d1dc01c/src/components/Utils/utils.ts#L14-L30

**Comment by melloware** [comment]
Thanks to @ClemensElflein 5.1.0 is now released to NPM.
