### ISSUE TITLE
Text Mode: Unnecessary scroll to top when the state is updated

### ISSUE THREAD

**Issue by Marlen0307** [melloware/react-logviewer#25]
Hi 👋 ,
I am using the log-viewer for fetching logs from a spring boot server. I am using an interval to constantly query the endpoint for fetching the logs. I am using the `text` property in order to display the logs. Here is the code snippet:

```ts
function App() {
  const [logArray, setLogArray] = useState<string[]>([]);

  const fetchLogs = useCallback(async () => {
    try {
      const response = await axios.get<LogResponse>(
        `http://localhost:8081/api/logs/`
      );
      const { logs } = response.data;

      setLogText((prev) => [...prev, ...logs]);
    } catch (error) {
      console.error(error);
    }
  }, []);

  useEffect(() => {
    const id = setInterval(fetchLogs, 5000);
    return () => {
      clearInterval(id);
    };
  }, [fetchLogs]);
  return (
    <>
      {logText.length > 0 ? (
        <div
          style={{
            width: "800px",
          }}
        >
          <LazyLog
            caseInsensitive
            enableHotKeys
            enableSearch
            height="520"
            width="800"
            text={logText.join("\n")}
          />
        </div>
      ) : (
        <>Loading...</>
      )}
    </>
  )
```

The problem that I am facing is that every time the `text` prop is updated the log viewer is rerendered which causes it to scroll back to the top. Is there a workaround to this?

**Comment by melloware** [comment]
@Marlen0307 yes changing the `text` will cause a re-render.  It sounds like you want the WebSocket mode where it updates your log or the URL mode?  

```xml
<LazyLog url="http://example.log" stream />
```

**Comment by Marlen0307** [comment]
@melloware Thank you for the quick reply! 
What you suggested is not really what I am looking for. I would like to send the request manually because I send some extra query parameters for getting chunks of the logs, in order to reduce network overload:
`http://localhost:8081/api/logs/all?lastPosition=50388`
Furthermore the backend does not stream the logs. It actually sends back the log from the `lastPostions` to the end of the file.
Do you have any suggestions for this case?

**Comment by melloware** [comment]
Hmmm I have only been using it the same way you do with `text` but my logs are after the fact so i am loading the whole log at once.    So once you "replace" the `text` its basically a normal React state change and re-renders the component.  You could possibly call ScrollTo or something to scroll to a particular line!

I have never really used the URL or WebSocket mode but the seemed to be more designed for your use case.   I have to admit i took over this component because you saw the main project had been basically abandoned so I am not a thorough expert on all facets of this component.

**Comment by melloware** [comment]
if you set `scrollToLine={50388}` does that scroll to the correct line?

**Comment by melloware** [comment]
@Marlen0307 have you tried `follow={true}` property?  According to the docs "Scroll to the end of the component after each update to the content. Cannot be used in combination with `scrollToLine`."

**Comment by hbtecSZE** [comment]
Hi,
I have a similar case. I fetch the data at intervals with a query to indicate which lines I am missing. It seems there’s no solution to handle this with the text mode. If fFollow is true, the view is stuck at the end, and if it’s false, it scrolls to the top at every update. Is there another way to input text without re-rendering the whole component if I don’t want to use WebSocket? The desired behavior would be: Scroll up -> Stay there, Scroll to the end -> Follow to the end.

Thanks for your Work!
