### ISSUE TITLE
How to add color to different parts of a line

### ISSUE THREAD

**Issue by Sshubam** [melloware/react-logviewer#29]
Hey actually i am using react lazy log for streaming logs from a websocket, however i want stuff like date, log level, message to be of different colours in the line.. how can I achieve that, can you please share any snippet or advice? 
Thanks.

**Comment by Sshubam** [comment]
@melloware i have full control over the log format... i just wanted to know how can I provide different volours to different parts of a line.. i read the docs but was unable to get it done

**Comment by Sshubam** [comment]
> if you paste an example log line from one of your logs I can show you...

[2024-05-05T11:16:35.920+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance:mainflow.init_run 1234 [queued]>

**Comment by Sshubam** [comment]
> OK Lazy log supports ANSI highlighting. See: https://melloware.github.io/react-logviewer/?path=/docs/stories-lazylog--docs
> 
> 
> 
> so that log line colored red.
> 
> 
> 
> ![image](https://github.com/melloware/react-logviewer/assets/4399574/96b25b31-36c9-4caa-b215-997bab536b8d)
> 
> 
> 
> Is just has ANSI tags wrapped around it like...
> 
> 
> 
> ```
> 
> \x1b[31mCreate file target/dist/css/libs.css failed\x1b[39m
> 
> ```
> 
> 
> 
> You can find all the ANSI tags here
> 
> 
> 
> ```js
> 
> const foregroundColors: AnisMap = {
> 
>     "30": "black",
> 
>     "31": "red",
> 
>     "32": "green",
> 
>     "33": "yellow",
> 
>     "34": "blue",
> 
>     "35": "magenta",
> 
>     "36": "cyan",
> 
>     "37": "white",
> 
>     "90": "grey",
> 
> };
> 
> const backgroundColors: AnisMap = {
> 
>     "40": "black",
> 
>     "41": "red",
> 
>     "42": "green",
> 
>     "43": "yellow",
> 
>     "44": "blue",
> 
>     "45": "magenta",
> 
>     "46": "cyan",
> 
>     "47": "white",
> 
> };
> 
> const styles: AnisMap = {
> 
>     "1": "bold",
> 
>     "3": "italic",
> 
>     "4": "underline",
> 
> };
> 
> ```
> 
> 
> 
> 

Oh i get it.. thank you so much.. i will try this out

**Comment by Sshubam** [comment]
@melloware do you know of any wrapper i can use to parse logs? 
example: [2024-05-05T11:16:35.920+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance:mainflow.init_run 1234 [queued]>

**Comment by Sshubam** [comment]
Thanks! It worked.. thanks a lot :D

**Comment by melloware** [comment]
i as going to say too Python might even have Ansi coloring in their log lib built in?

**Comment by Sshubam** [comment]
> i as going to say too Python might even have Ansi coloring in their log lib built in?

I meant parsing a log file in python to render in lazylog
