### ISSUE TITLE
Can I make texts autoWrap?

### ISSUE THREAD

**Issue by XijueYZ** [melloware/react-logviewer#35]
I hope that when a log entry is very long, there won't be a horizontal scrollbar and it can automatically wrap to the next line.
How should I do it?

**Comment by melloware** [comment]
I have not studied it thoroughly but i believe the answer is no.  the way the log viewer is designed with formatting etc that each log line must be an entire line and not wrapped.

**Comment by deivid11** [comment]
This is a good alternative ;) https://www.patternfly.org/extensions/log-viewer/

**Comment by melloware** [comment]
@deivid11 i actually looked at that component before I found React Lazy Log and did not like that component as much as this one or nearly as feature full.  (Minus this feature of course)!

**Comment by shalins** [comment]
This would be great if it could be added, I feel line wrapping is quite fundamental for a tool like this.

**Comment by HunterCFigueroa** [comment]
Would love to help with this: https://github.com/melloware/react-logviewer/issues/54

**Comment by melloware** [comment]
There will be a `wrapLines` property in the 6.0.0 release
