### ISSUE TITLE
Using ScrollFollow results in maximum updates exceeded error

### ISSUE THREAD

**Issue by kevinvugts** [melloware/react-logviewer#36]
Hi, when using the auto scroll functionality it currently results in an infinite loop.

**Comment by melloware** [comment]
can you put together a StackBlitz example showing the issue?

**Comment by kevinvugts** [comment]
@melloware I figured out that the issue happens when the outer div containing the <ScrollFlow /> doesn't have an height, the issue occurs. When you set an height on the outer div, the issue is gone

**Comment by melloware** [comment]
@kevinvugts can you post your sample code that works?  I would like to update the README.MD.  The current docs

```js
import React from "react";
import { render } from "react-dom";
import { LazyLog, ScrollFollow } from "@melloware/react-logviewer";

render(
    <ScrollFollow
        startFollowing={true}
        render={({ follow, onScroll }) => (
            <LazyLog url="http://example.log" stream follow={follow} onScroll={onScroll} />
        )}
    />,
    document.getElementById("root"),
);
```

**Comment by melloware** [comment]
@kevinvugts  ?

**Comment by kevinvugts** [comment]
> @kevinvugts ?

GOodmorning melloware,

Just simply wrap the <ScrollFollow /> with a div containing a fixed height 

```
<div style={{ height: 500, width: 902 }}>
  <ScrollFollow
    startFollowing
    render={({ onScroll, follow, startFollowing, stopFollowing }) => (
      <LazyLog extraLines={1} enableSearch url={url} stream onScroll={onScroll} follow={follow} />
    )}
  />
</div>```

**Comment by melloware** [comment]
Thanks docs updated!  https://github.com/melloware/react-logviewer/blob/main/README.md
