### ISSUE TITLE
`undefined` while filtering with line numbers

### ISSUE THREAD

**Issue by benbek** [melloware/react-logviewer#48]
While filtering logs and displaying line numbers, the last log lines have an `undefined` label as their line number when `extraLines` is greater than 0.
This can be easily reproduced in Storybook:
![image](https://github.com/user-attachments/assets/61a2a3c5-e0ad-4b62-9038-4b9b3c1bf53b)
Notice I filtered by an existing token, and the last line does contain `undefined`.

I suggest fixing it by checking whether `number` is undefined in the `renderRow` [function](https://github.com/melloware/react-logviewer/blob/main/src/components/LazyLog/index.tsx#L993) – see link for where I think the fix should be.
I can open a PR that fixes that. This is how I imagine the end result:
![image](https://github.com/user-attachments/assets/4663d494-a61d-446d-95c5-82f706343ef5)

**Comment by melloware** [comment]
a PR would be awesome @benbek !
