### ISSUE TITLE
`enableLinks` breaks JSON line logs

### ISSUE THREAD

**Issue by edgarrmondragon** [melloware/react-logviewer#50]
A log line 

```jsonl
{"level":"info","timestamp":"2024-10-28T14:16:06Z","event":"This is a link to https://example.com/"}
```

is rendered as

```html
<a class="log-part" href="https://example.com/&quot;}
" target="_blank" rel="noopener noreferrer">https://example.com/"}
</a>
```

**Comment by melloware** [comment]
Definitely a bug

**Comment by melloware** [comment]
Actually no an HTML link inside of JSON doesn't make sense.   I would not use `enableLinks` with JSON code and I think this ticket is of more interest: https://github.com/melloware/react-logviewer/issues/30

**Comment by edgarrmondragon** [comment]
Thanks, makes sense!
