### ISSUE TITLE
ScrollFollow does not activate 'follow' when using the extraLines param

### ISSUE THREAD

**Issue by chetverikov** [melloware/react-logviewer#53]
When I use the extraLines parameter with follow, the ScrollFollow component cannot correctly calculates the values on line [78](https://github.com/melloware/react-logviewer/blob/main/src/components/ScrollFollow/index.tsx#L72), because "ScrollFollow" does not scroll to the last line, but the condition waits for the last line.

The fix is here https://github.com/melloware/react-logviewer/pull/52

**Comment by melloware** [comment]
Thanks I just pushed 5.3.1 to NPM !
