### ISSUE TITLE
Any blockings to release 6.0 version?

### ISSUE THREAD

**Issue by thlmenezes** [melloware/react-logviewer#61]
Firstly, nice work on rapidly reviewing PRs and adding new features to this library; I saw the updates on #55 and the fast iteration process on the PR.

I was expecting to use the `wrapLines` feature as soon as it ships, but it is planned for release 6.0, without an release date.

The related milestone already has 100% completion, so is there an expected release date for 6.0 version? Are there any blocking issues to release 6.0?

https://github.com/melloware/react-logviewer/milestone/16
![image](https://github.com/user-attachments/assets/8309361b-296a-4853-ad4e-d4506240a15a)

**Comment by melloware** [comment]
Yep let me release today as I think it's good enough for people to use and report any bugs!  After I deploy please let me know how the testing goes!

**Comment by melloware** [comment]
I am waiting to hear from @HunterCFigueroa just in case he has anything else he wants to get in before I release.

**Comment by HunterCFigueroa** [comment]
I don't have anything else lined up, and I think there is already plenty for a solid release. Good to go on my end 😁

**Comment by melloware** [comment]
Great!  I will release in the morning.

**Comment by melloware** [comment]
6.0.0 Released!

**Comment by thlmenezes** [comment]
@melloware I believe the current 6.0 version published to npm contains old code, could you review and update the release?

### More Info

parseLinks implementation is not updated, so the bug #64 can still be reproduced in 6.0

![image](https://github.com/user-attachments/assets/6658b22c-333e-4e5d-b48a-bca73d3a1c51)

![image](https://github.com/user-attachments/assets/5765de44-651a-4f5b-a69e-bd0fdb847cb9)

Could not find wrapLines prop from #55 

![image](https://github.com/user-attachments/assets/c30d2e09-78be-4622-a202-2310b46a3a98)

**Comment by melloware** [comment]
Weird let me look I did the same release process I always do.

**Comment by melloware** [comment]
OK try 6.0.1

**Comment by thlmenezes** [comment]
@melloware it worked on 6.0.1, thank you
