### ISSUE TITLE
Search: Allow control over minimum search chars

### ISSUE THREAD

**Issue by maksimlya** [melloware/react-logviewer#65]
Hi, is there a way to enable search with shorter input?

Currently I have an issue, I try to search number '20' for example, but it waits for a longer input.

Concatinating it with other input didnt work for me either, example:

 log line - 'firm number 20'

If I write 'firm number ' - search highlights the line, but once I add number 2, it is gone.

Only writing '20' doesn't works either for lengh reason. Currently using version 5.1.1, thx in advance.

**Comment by melloware** [comment]
@maksimlya i think i need to fix this to allow the number of characters to be configured instead of hard coded to 3.

**Comment by melloware** [comment]
OK in 6.0.2 there is a new `searchMinCharacters` that you can set to 0 if you want to search by any number of characters.

**Comment by melloware** [comment]
6.0.2 is now in NPM
