### ISSUE TITLE
React Window Infinite Loader Support

### ISSUE THREAD

**Issue by mmadson** [melloware/react-logviewer#8]
https://www.npmjs.com/package/react-window-infinite-loader

Wondering if this is already possible but let's say we have a crazy large file that we can paginate over the lines and we know up front how many lines are in the file. I'd like have the full scroll bar present and be able to jump to parts of the file and then have the react window infinite loader load the relevant files.

Similar to this demo.

https://codesandbox.io/s/5wqo7z2np4

Apologies if this is already supported and I just missed it. 

Thank you for putting in the work to keep this project alive. =)

**Comment by melloware** [comment]
@mmadson this is great feedback. I was unaware of the infinite loader it definitely seems possible.  It is definitely NOT implemented currently.  I will mark it as an enhancment.

**Comment by HunterCFigueroa** [comment]
Would love to help with this: https://github.com/melloware/react-logviewer/issues/54
